namespace VestedAI.ConnectorSdk.Tool;

/// <summary>
/// Normalized tool declaration derived from <see cref="ToolAttribute"/> on a
/// <see cref="ToolHandler{TArgs,TResult}"/> subclass.
/// Schemas are stored as raw JSON strings generated by NJsonSchema at registration time.
/// </summary>
public sealed class ToolDeclaration
{
    /// <summary>Dot-namespaced tool key (e.g. "myapp.orders.get").</summary>
    public required string Key { get; init; }

    /// <summary>Display name (falls back to Key when the attribute Name is empty).</summary>
    public required string Name { get; init; }

    /// <summary>Human-readable description shown to the LLM.</summary>
    public required string Description { get; init; }

    /// <summary>
    /// Sensitivity value, one of <see cref="Sensitivity.All"/>, or empty string meaning "unset".
    /// </summary>
    public required string Sensitivity { get; init; }

    /// <summary>Per-call timeout in milliseconds.</summary>
    public required int DefaultDeadlineMs { get; init; }

    /// <summary>Maximum serialised result size in bytes.</summary>
    public required int MaxResultBytes { get; init; }

    /// <summary>JSON Schema for the TArgs POCO, as a raw JSON string.</summary>
    public required string InputSchemaJson { get; init; }

    /// <summary>JSON Schema for the TResult POCO, as a raw JSON string. May be null.</summary>
    public string? OutputSchemaJson { get; init; }

    /// <summary>The concrete handler class (subtype of ToolHandler&lt;,&gt;).</summary>
    public required Type HandlerType { get; init; }

    /// <summary>The TArgs POCO type used for deserialization.</summary>
    public required Type ArgsType { get; init; }

    /// <summary>The TResult type.</summary>
    public required Type ResultType { get; init; }

    /// <summary>
    /// Create a handler instance and delegate to its InvokeBoxedAsync.
    /// The handler is instantiated fresh per call (stateless handlers expected).
    /// </summary>
    public Task<object> InvokeAsync(object args, ToolContext ctx)
    {
        var handler = (ToolHandlerBase)Activator.CreateInstance(HandlerType)!;
        return handler.InvokeBoxedAsync(args, ctx);
    }
}
